service: serverless-api
frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  stage: ${self:custom.currentStage}

custom:
  currentStage: dev
  projectName: serverless-api
  #only for local development
  # serverless-offline:
  #   httpPort: 5000
  #   lambdaPort: 5001

#only for local development
# plugins:
#   - serverless-offline

resources:
  - ${file(resources/apigateway.yml)}
  - ${file(resources/api-gateway-errors.yml)}
  - ${file(resources/iam-roles.yml)}
