Resources:
  ApiGatewayRestApi:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: ${self:service}-api-${self:custom.currentStage}
      EndpointConfiguration:
        Types:
          - EDGE
      Policy: ""

Outputs:
  ApiGatewayRestApiId:
    Value:
      Ref: ApiGatewayRestApi
    Export:
      Name: ${self:custom.currentStage}-ExtApiGatewayRestApiId

  ApiGatewayRestApiRootResourceId:
    Value:
      Fn::GetAtt:
        - ApiGatewayRestApi
        - RootResourceId
    Export:
      Name: ${self:custom.currentStage}-ExtApiGatewayRestApiRootResourceId
